/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DashboardRoleRouteImport } from './routes/dashboard.$role'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as DashboardStudentIndexRouteImport } from './routes/dashboard.student.index'
import { Route as DashboardStudentAttendanceRouteImport } from './routes/dashboard.student.attendance'
import { Route as DashboardStudentAiRouteImport } from './routes/dashboard.student.ai'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleRoute = DashboardRoleRouteImport.update({
  id: '/dashboard/$role',
  path: '/dashboard/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardStudentIndexRoute = DashboardStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentAttendanceRoute =
  DashboardStudentAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentAiRoute = DashboardStudentAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/student/ai': typeof DashboardStudentAiRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/student/ai': typeof DashboardStudentAiRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student': typeof DashboardStudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/student/ai': typeof DashboardStudentAiRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboards'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/$role'
    | '/dashboard/student'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/student/ai'
    | '/dashboard/student/attendance'
    | '/dashboard/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboards'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/$role'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/student/ai'
    | '/dashboard/student/attendance'
    | '/dashboard/student'
  id:
    | '__root__'
    | '/'
    | '/dashboards'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/$role'
    | '/dashboard/student'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/student/ai'
    | '/dashboard/student/attendance'
    | '/dashboard/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardsRoute: typeof DashboardsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SignupRoute: typeof SignupRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DashboardRoleRoute: typeof DashboardRoleRoute
  DashboardStudentRoute: typeof DashboardStudentRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$role': {
      id: '/dashboard/$role'
      path: '/dashboard/$role'
      fullPath: '/dashboard/$role'
      preLoaderRoute: typeof DashboardRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student/': {
      id: '/dashboard/student/'
      path: '/'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof DashboardStudentIndexRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/attendance': {
      id: '/dashboard/student/attendance'
      path: '/attendance'
      fullPath: '/dashboard/student/attendance'
      preLoaderRoute: typeof DashboardStudentAttendanceRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/ai': {
      id: '/dashboard/student/ai'
      path: '/ai'
      fullPath: '/dashboard/student/ai'
      preLoaderRoute: typeof DashboardStudentAiRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardStudentRouteChildren {
  DashboardStudentAiRoute: typeof DashboardStudentAiRoute
  DashboardStudentAttendanceRoute: typeof DashboardStudentAttendanceRoute
  DashboardStudentIndexRoute: typeof DashboardStudentIndexRoute
}

const DashboardStudentRouteChildren: DashboardStudentRouteChildren = {
  DashboardStudentAiRoute: DashboardStudentAiRoute,
  DashboardStudentAttendanceRoute: DashboardStudentAttendanceRoute,
  DashboardStudentIndexRoute: DashboardStudentIndexRoute,
}

const DashboardStudentRouteWithChildren =
  DashboardStudentRoute._addFileChildren(DashboardStudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardsRoute: DashboardsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SignupRoute: SignupRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DashboardRoleRoute: DashboardRoleRoute,
  DashboardStudentRoute: DashboardStudentRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
